name: Publish

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Generate Tag
        id: tag
        run: |
          echo ::set-output name=POST_TAG::$(date +%Y.%m.%d)
      - name: Build and push containers.monetr.dev
        uses: docker/build-push-action@v1
        with:
          registry: containers.monetr.dev
          username: ${{ secrets.containers_push_username }}
          password: ${{ secrets.containers_push_password }}
          tags: latest,${{ steps.tag.outputs.POST_TAG }}
          repository: pgtest
      - name: Build and push ghcr.io
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: latest,${{ steps.tag.outputs.POST_TAG }}
          repository: monetr/pgtest
  pg-test:
    needs:
      - docker
    name: Test
    runs-on: ubuntu-latest
    container: ghcr.io/monetr/pgtest:latest
    env:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: postgres
      POSTGRES_DB: test-db
      POSTGRES_HOST_AUTH_METHOD: trust
    services:
      postgres:
        image: ghcr.io/monetr/pgtest:latest
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: postgres
          POSTGRES_DB: test-db
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: '/junit.xml'
